name: twofauth
description: 2FA manager based on 2FAuth web app.
publish_to: 'none'

version: 0.5.2

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: "3.35.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  dio: ^5.9.0
  path_provider: ^2.1.5
  flutter_svg: ^2.2.0
  crypto: ^3.0.6
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
